### ISSUE TITLE
Some cards do not expand under their button (Google Chrome)

### ISSUE THREAD

**Issue by cernec1999** [0x90skids/0x90skids.github2.io#45]
**Describe the bug**
Some cards do not expand under their button after merging the latest PR 

**To Reproduce**
1. Go to https://0x90skids.com/ctf/ in Google Chrome
2. Click on ```Stranger-Servers```
3. Optionally expand ```simplecalc```

The cards will be wrongly placed

**Expected behavior**
The cards should be under their respective buttons

**Screenshots**
<img width="847" alt="Screen Shot 2020-07-27 at 9 39 31 AM" src="https://user-images.githubusercontent.com/5413945/88548983-c7880380-cfed-11ea-8e69-fb1c5c2a6404.png">

**Desktop:**
 - OS: macOS Catalina
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)

@tcbutler320

**Comment by fbibeau** [comment]
Fixed & merged in PR #46
